// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Category = "health" | "fitness" | "nutrition" | "leisure" | "productivity" | "finace" | "personalGrowth" | "social" | "creative" | "study" | "home" | "work" | "school" | "morning" | "afternoon" | "evening" | "night" | "other";

export type Habit = { title: string, description: string, status: HabitStatus, streak: Streak, completions: number, theme: Theme, category: Category, reminder: Reminder | null, created: string, updated: string | null, };

export type HabitStatus = "completed" | "onGoing" | "archived";

export type Reminder = "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";

export type Streak = "daily" | "weekly" | "monthly";

export type Theme = "red" | "green" | "blue" | "rose" | "mint" | "sky" | "amber" | "indigo" | "neutral";
