// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Commit = {
  id: number | null;
  habitId: number;
  note: string | null;
  image: string | null;
  created: string;
  updated: string | null;
  completion: number;
  completed: boolean;
  completionDate: string | null;
};

export type Habit = {
  id: number | null;
  title: string;
  description: string;
  status: HabitStatus;
  streak: HabitStreak;
  completions: number;
  theme: HabitTheme;
  category: HabitCategory;
  reminder: HabitReminder | null;
  created: string;
  updated: string | null;
};

export type HabitCategory =
  | "health"
  | "fitness"
  | "nutrition"
  | "leisure"
  | "productivity"
  | "finace"
  | "personalGrowth"
  | "social"
  | "creative"
  | "study"
  | "home"
  | "work"
  | "school"
  | "morning"
  | "afternoon"
  | "evening"
  | "night"
  | "other";

export type HabitReminder = "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";

export type HabitStatus = "completed" | "onGoing" | "archived";

export type HabitStreak = "daily" | "weekly" | "monthly";

export type HabitTheme =
  | "red"
  | "green"
  | "blue"
  | "rose"
  | "mint"
  | "sky"
  | "amber"
  | "indigo"
  | "neutral";

export type MonthTimeline = { nodes: Array<string> };

export type UserSettings = {
  id: number;
  theme: string;
  highlightCurrentDay: boolean;
  showCategoryFilter: boolean;
  defaultTimeline: string;
};

export type WeekTimeline = { nodes: Array<string> };

export type YearTimeline = { nodes: { [key in string]?: Array<string> } };
